1. Implementation of StudentList
Gheorghi/java-collections-list pull request #1
Opened 2021-09-21 09:49 UTC by Gheorghi

Please review

2021-09-21 11:08 UTC, evgheni-panenco requested changes

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +    private static int CAPACITY = 10;
It's a constant, can be marked final as well

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +    private static Student[] elements = new Student[CAPACITY];
Static means that this variable will be the same for all instances of StudentList, which is not we expect from arraylist. Please remove static.

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +    private static Student[] elements = new Student[CAPACITY];
Logic with memory allocation can be moved to constructors. In this case we can remove memory reallocation from StudentList(capacity) constructor.

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +        updateCapacity(elements, initialCapacity);
Check the 2nd comment on line 13.

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +@ToString
Do we need this @ToString and does it used anywhere?

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +public class StudentList extends AbstractList<Student> implements List<Student> {
Why do we need to extend AbstractList? Please remove this part

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +        return new Iterator<Student>() {
There are two types of iterator fail-safe and fail-fast (google it).
From documentation arraylist iterator should be fail-fast - https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#iterator--

That means it should throw an exception in case if collection was modified.

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +            ts[size()] = null;
why do we need to assignee null to the last element?

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +            Student[] beforeIndex = Arrays.copyOfRange(elements, 0, i + 1);
why do we need to create 3 arrays in order to add element to the specific index.

you can move all creation logic into one method and call it from the 2nd

as an example, let's imagine that you already implemented add(index, student) method,
than in add(student) you can just call this method:
`
public void add(Student student) {
   add(theLastIndex, student);
}
`

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +            Student[] beforeIndex = Arrays.copyOfRange(elements, 0, i + 1);
please consider to refactor this logic. as analog you can use remove() method that we already implemented without these memory allocations on each action.

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +    private void mergeTheArray(Student[] beforeIndex, Student[] afterIndex, int lengthOfBefore, int lengthOfAfter) {
can be removed after refactor

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +        if (index != -1) {
all this method (except the first line) can be moved to another one - remove(index)
from this method you can just determine the index and then call remove(index) function

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +        for (int i = 0; i < size(); i++) {
no need to null all elements, just reassign elements
`elements = new StudentList[someCapacity]`
and then update size of the array

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +    static void subListRangeCheck(int from, int to, int arraySize) {
what it the purpose of static here?

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +    private boolean checkTheExistanceOfIndex(int index) {
This method throws an exception if index is out of bound, then it returns true.
I think we can remove this return value, which will reduce if statement where we use the result of this method.

This method can return void and just throw an exception if needed.

2021-09-21 11:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +    private boolean checkIndex(int index) {
same as for checkTheExistanceOfIndex(index)

2021-09-21 14:24 UTC, Gheorghi commented on src/main/java/com/endava/internship/collections/StudentList.java
> +            ts[size()] = null;
If elements can be added in the specified array with room to save, the last element in the array of the collection is set to null.

2021-09-22 08:08 UTC, evgheni-panenco requested changes

2021-09-22 08:08 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentList.java
> +            int capacity = elements.length + 10;
first way with multiplying by 2 was better

2021-09-22 08:26 UTC, evgheni-panenco approved these changes

2021-09-22 08:27 UTC, merged